tonarino/actor

src/lib.rs
On integrating the new actor system with tonari's main codebase, the type system showed more restrictiveness than was necessary, making it impossible to run an `Actor` on the main thread if `Actor` didn't implement `Send` (which of course is unnecessary if not being spawned on a separate thread).
=> relax constraints on Send in System and SpawnBuilder

src/lib.rs
Kinda interesting that this worked before. Apparently, Box<Fn*> implements Fn*:
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-FnOnce%3CArgs%3E
=> chore: remove one boxing

Cargo.toml, benches/benches.rs, examples/echo.rs, examples/media_pipeline.rs, examples/simple_timer.rs, src/lib.rs, src/timer.rs
From #14
This feels a lot simpler than using `hierarchical_hash_wheel_timer`.
It does the dumb thing which is to just keep a `Vec` of tasks and tick every millisecond (or a configurable timer resolution). It iterates over each task and runs if it has expired, and reschedules it if it's a recurring task.
CPU usage is noticeably lower compared to `hierarchical_hash_wheel_timer` but it likely doesn't scale as well with lots and lots of timers in comparison.
=> Simple Timer

benches/benches.rs, examples/actor_wrapping.rs, examples/delay_actor.rs, examples/echo.rs, examples/media_pipeline.rs, examples/simple_timer.rs, src/lib.rs
This makes whole Context parametrised by M (message), rather than A: Actor.
As a result, Context is more flexible to pass on, which facilitates creation
of Actor wrappers.
This changes the signature of the Actor trait methods, which breaks the API,
though required edits should be mostly mechanical. The field `myself` was
arguably used most for sending messages to oneself, which already went
through a `Deref` to `Recipient`.
One piece of functionality was lost on Context: the `Addr::recipient()`
method which can produce a "converting" recipient.
`recipient()` can be moved from `Addr` to `Recipient` to preserve it.
Do you think it is needed?
=> Context: change myself field from Addr<A> to Recipient<M>

benches/benches.rs, examples/actor_wrapping.rs, examples/delay_actor.rs, examples/echo.rs, examples/media_pipeline.rs, examples/simple_timer.rs, src/lib.rs, src/timed.rs
See module level docs and `delay_actor.rs` example for info.
When actor A wants to send a delayed message to actor B, there are 3 places where the queue can be:
1. in actor (thread) A
2. in some separate actor (thread) C
3. in actor (thread) B.
This PR choses option 3. In our downstream usage, all recurring messages are "to self", so options 1. and 3. are functionally (but not API-wise) equivalent. The chosen approach has some pros and cons:
- pro: modulo the preparatory "independent" core API changes, Timed<> wrapper and friends are strictly separate form the core API (could have been implemented in a separate crate).
- pro: avoids having to pass some `DelayActor` reference around, or having it registered as some global resource.
- pro: delayed messages do not cross thread boundary (in …
=> Add Timed actor wrapper + friends for delayed/recurring messages

src/lib.rs
We're going to touch it, the tests will demonstrate the changes.
This aids with debugging send errors. Thanks to type decoupling made by
`Recipient`, senders may not even know the actual receiving actor, so
senders cannot replicate this behaviour fully on their own.
Should help with debugging downstream issues like tonarino/portal#1153.
Caveats:
- Increases the size of `Recipient`, `Addr`, `SendError` by ~one pointer~ two pointers (one `&str`).
- Introduces API-breaking changes to `SendError` and `SendResultExt::on_full()`.
- ~Specifically, SendError, DisconnectedError can no longer be constructed by downstream code. That feels correct now, but can be fixed in non-API-breaking manner if needed.~ - no longer true after the last commit.
---
Is it worth it?
=> RFC: Include intended recipient name in SendError

Cargo.toml, src/lib.rs
This is a prerequisite for message priorities #22 - crossbeam has built-in
randomization when receiving messages, while flume lets us control that
using a feature flag.
flume's API is largely the same as crossbeam's, only real difference is
that select() is constructed using builder pattern rather than a macro.
Actor own benchmark result change (crossbeam -> flume):
```
circular/circular (2 actors)
time:   [3.0926 ms 3.1223 ms 3.1528 ms]
thrpt:  [317.18 Kelem/s 320.28 Kelem/s 323.35 Kelem/s]
change:
time:   [-24.762% -21.495% -17.992%] (p = 0.00 < 0.05)
thrpt:  [+21.940% +27.380% +32.912%]
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
1 (1.00%) high mild
2 (2.00%) high severe
circular/circular (native CPU count - 1)
time:   [3.9945 ms 4.0224 ms 4.0493 ms] …
```
=> Port from crossbeam-channel to flume

examples/actor_wrapping.rs, src/lib.rs, src/timed.rs
Would have to accept extra parameter once we add priority channel.
That would be well possible, but perhaps this method in not really needed
once we have prio channels? Let's try without it first.
Actor trait has gained new optional method `priority(message: &M)` which
determines priority of each message before being sent.
`Addr` grows by one extra `flume::Receiver`. `Recipient` doesn't grow as its
`message_tx` payload is boxed.
When porting portal to use priority channels, I've realized actor systems may
want to set capacity of the normal channel as low as 1 (for actors that cannot
keep up with the pace, but for which that doesn't matter).
Producers of their "bulk" low-priority messages will usually ignore their
channels being full. OTOH producers of their important high-priority …
=> Add high priority message channel for each actor

src/lib.rs
This is a tiny struct size optimization, because multiple Recipients share a single MessageSender
through an Arc.
But more importantly this allows us to implement the next commit (add priority to error types) more
cleanly.
This should help with diagnosing actor channel full errors.
Also changes signature of the callback accepted by SendErrorExt::on_full() method, which is
a breaking change.
Thanks @bschwind for pointing-out zero-capacity flume channels are special.
=> Add `priority` field to `SendError`, `DisconnectedError`

examples/delay_actor.rs, src/lib.rs
I claimed this in the previous PR, but it wasn't true: if the actor spawned quick enough the test
would fail. What _was_ true is that I've ran the testsuite hundreds of times in a loop, and it
didn't fail. Some strange coincidence?
Make it truly deterministic by not spawning the actor at all (test using a naked `Addr`).
This makes the API more flexible as we now can call `.recipient()` multiple times in a row on the
same value, allowing one more M -> N message conversion in each step.
Previously, we thought it is too wild to create "arbitrarily long conversion chain", so we've put
`.recipient()` on `Addr`, only allowing one such conversion.
But with the advent of actor wrappers like `Timed<A>`, this first conversion is "consumed" by the
wrapper itself, limiting their users.
The method …
=> Move `.recipient()` from `Addr` to `Recipient`, Capacity fields public

examples/actor_wrapping.rs, examples/delay_actor.rs, examples/echo.rs, src/lib.rs, src/timed.rs
I'm myself not convinced about this, but publishing for feedback anyway.
Resolves #70 (I apparently forgot about this PR when writing the issue; it even shows that defaults for associated constants are possible/stable).
=> Allow specifying default capacities on actors themselves

src/lib.rs
We did this for the main repo a while ago, cleaning up my working tree.
=> Use Arc::clone(&variable) instead of variable.clone()

src/lib.rs, src/timed.rs
This test fails (as of this commit) with
```
---- timed::tests::recurring_messages_for_busy_actors stdout ----
thread 'timed::tests::recurring_messages_for_busy_actors' panicked at 'assertion failed: `(left == right)`
left: `[1, 3, 3]`,
right: `[1, 2, 3, 2, 3]`', src/timed.rs:318:9
```
I.e. messages of type 2 (delayed) are never delivered.
This fixes the recurring_messages_for_busy_actors test, and should fix #72.
---
_Please give the contained logic thorough review scrutiny, this is a central thing._
=> Fix timed messages for busy actors

Cargo.toml
Let's be up-to-date before a release. Logs in tests and benches still work.
```
strohel@thicky ~/work/actor $ cargo outdated
All dependencies are up to date, yay!
```
- depends on #73, which should be merged first (for clippy fix)
=> Update criterion and env_logger dev dependencies

src/lib.rs, src/timed.rs
Fixes clippy 1.73 lint.
This different order makes sense, as it avoids an expect().
I must have been mistaken when originally introducing `clippy:all`, because these are, by definition, lints that are enabled without any configuration: https://doc.rust-lang.org/stable/clippy/usage.html#lint-configuration
Add a lint that catches `todo!()` (but allows `panic!()`, `unreachable!()`, `unimplemented!()`) - you're encouraged to use it during development as a reminder for stuff to finish before a change can be merged.
=> Fix clippy 1.73 lints, update lint configuration

Cargo.toml, benches/pub_sub.rs, examples/actor_wrapping.rs, examples/pub_sub_example.rs, examples/simple_timer.rs, src/lib.rs
This is a follow-up to #82 to make it a hard error when the user forgets to provide an address to an actor.
This breaks the API because now one has to call `.with_default_capacity()` if they really don't want to provide or configure the address.
Please let me know how to navigate the upgrade process. I only bumped the Cargo version but we'll also have to publish this, possibly prepare a changelog, etc.
=> Make spawn builder harder to misuse

Cargo.toml, benches/pub_sub.rs, rustfmt.toml, src/lib.rs, src/timed.rs
and let subscribers receive it upon subscription.
Optionally, we could provide a separate marker trait for cached events and persist only those. I couldn't figure out how to dynamically query for the type (trait) in `publish`. Somehow `downcast_ref` is not implemented for `Event` (despite `Event` being `Any`). I'd appreciate some help with that.
This causes performance regression for the pub-sub system. Here's output of `cargo bench --bench pub_sub` running on this branch (comparing it to the previous run on `main`):
<details><summary>Details</summary>
<p>
```
Compiling tonari-actor v0.9.0 (/Users/jentak/workspace/tonari/actor)
Finished `bench` profile [optimized] target(s) in 1.20s
Running benches/pub_sub.rs (target/release/deps/pub_sub-9cceefaff682ce83)
publish/1 publishers 10 …
```
=> Cache last published event

benches/benches.rs, src/lib.rs, src/timed.rs
- require Display instead of Debug for Actor::Error associated type
- print handle() (and friends) errors using `{:#}` rather than `{:?}`
- this hides the backtrace print of anyhow errors
- differentiate handle() (and friends) errors while shutting down vs. running and log them with lower severity
- make it more clear and less spammy when trying to shut down a system while it is already shutting down
This is a semver-breaking change (due to the new bound on Actor::Error).
=> Error reporting QoL

benches/pub_sub.rs, examples/actor_wrapping.rs, examples/pub_sub_example.rs, examples/simple_timer.rs, src/lib.rs, src/timed.rs
- on top of #88
I've long time wanted to do this, other work on actor has finally triggered me.
This should allow removing almost all remaining occurrences of fallible `.unwrap()` / `.expect()` in our downstream code.
It is (obviously) semver-breaking change which causes a bit of churn to adapt to, but the fact of adapting itself should be a nice cleanup.
=> Make `Actor::started()`, `stopped()` fallible

src/lib.rs
And move one impl to parent scope.
=> Fix clippy 1.83 lints (elide lifetimes)
